---
title: "Exponential offset"
output: html_notebook
---


```{r, fig.width=15, fig.height=10}
par(mfrow=c(1,1), mar=c(5, 4, 4, 2) + 0.1)
x<-(1:15000)/100
plot(x, dexp(x, rate=0.2), t="l", lwd=4, xlab="Time", ylab="density", xlim=c(-50, 50), ylim=c(0, 0.19), cex.lab=1.5)
x2 <- x - 40
lines(x2, dexp(x, rate=0.2), t="l", lwd=4, col="red")
legend(legend=c("dExponential(rate=0.2)", "dExponential(rate=0.2, offset=-40.0)", "Fossil age", "Probability of observing\nspeciation_clade_Anthropoidea=-40 (~0.037)"), lwd=c(3, 3, 5, 5), col=c("black", "red", "blue", "grey"), "topright", cex=1.5, lty=c(1,1,3, 2))
abline(v=-31.5, col="blue", lwd=5, lty=3)
polygon(x=c(-40, -60, -60, -40), y=c(-0.1, -0.1, 0.3, 0.3), col=rgb(0.3, 0.3, 0.3, 0.1), border=NA)
abline(h=dexp(rate=0.2, x=40-31.5), col="grey", lwd=5, lty=2)
abline(h=0.0, col="grey", lty=4)
abline(v=0.0, col="grey", lty=4)
```


```{r}

x3 <- (1:15000)/100 - 181.5

par(mfrow=c(1,1), mar=c(5, 4, 4, 2) + 0.1)
plot(x3, dexp(x[order(x, decreasing = T)], rate=0.2), t="l", lwd=4, col="red", ylab="Prior density", xlab="Clade age", xlim=c(-80, -30))
#legend(legend=c("dExponential(rate=0.2)", "dExponential(rate=0.2, offset=-40.0)", "Fossil age", "Probability of observing\nspeciation_clade_Anthropoidea=-40 (~0.037)"), lwd=c(3, 3, 5, 5), col=c("black", "red", "blue", "grey"), "topright", cex=1.5, lty=c(1,1,3, 2))
abline(v=-31.5, col="blue", lwd=5, lty=3)
abline(h=0.0, col="grey", lty=4)
abline(v=0.0, col="grey", lty=4)


```



